application: coremic
version: 1
runtime: python27
api_version: 1
threadsafe: true

instance_class: F4
automatic_scaling:
  max_idle_instances: 1
  min_idle_instances: 0

handlers:
- url: /_ah/pipeline.*
  script: pipeline.handlers._APP

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: coremic.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: numpy
  version: "1.6.1"
- name: matplotlib
  version: "1.2.0"

