application: coremic
version: 2
runtime: python27
api_version: 1
threadsafe: false

instance_class: F1
automatic_scaling:
  min_idle_instances: 0

handlers:
- url: /_ah/pipeline.*
  script: pipeline.handlers._APP

- url: /static
  static_dir: static
  application_readable: true

- url: /.*
  script: src.routing.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: numpy
  version: "1.6.1"
- name: matplotlib
  version: "1.2.0"
- name: jinja2
  version: "2.6"

