application: coremic
version: 1
runtime: python27
api_version: 1
threadsafe: true

instance_class: F4_1G

# top to bottom priority
handlers:
- url: /_ah/pipeline.*
  script: mapreduce.lib.pipeline.handlers._APP
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: coremic.app

includes:
- lib/mapreduce/include.yaml

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: numpy
  version: "1.6.1"
- name: matplotlib
  version: "1.2.0"

