core = [
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Xanthobacteraceae;g__Labrys;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00342857142857,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Rhizobiaceae',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': 0.04,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Alteromonadales;f__OM60;g__;s__',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': 0.04,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Acidobacteria;c__BPC102;o__MVS-40;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.024,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Actinobacteria;c__Actinobacteria;o__Actinomycetales;f__Pseudonocardiaceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00342857142857,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Paenibacillaceae;g__Paenibacillus;s__chondroitinus',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00342857142857,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Acidobacteria;c__BPC102;o__;f__;g__;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00342857142857,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Deltaproteobacteria;o__Desulfuromonadales;f__Geobacteraceae;g__Geobacter;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00342857142857,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Bacteroidetes;c__Cytophagia;o__Cytophagales;f__Cytophagaceae;g__Dyadobacter;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00342857142857,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Verrucomicrobia;c__Verrucomicrobiae;o__Verrucomicrobiales;f__Verrucomicrobiaceae;g__;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00342857142857,
        'threshold': 75
    },
    {
    'otu': 'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.024,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Sphingomonadales;f__Sphingomonadaceae;g__Sphingobium;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.024,
        'threshold': 75
    },
    {
        'otu': 'k__Bacteria;p__Bacteroidetes;c__Flavobacteriia;o__Flavobacteriales;f__[Weeksellaceae];g__Chryseobacterium;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.0226666666667,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Xanthobacteraceae;g__Labrys;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00485714285714,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Rhizobiaceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00485714285714,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Bacteroidetes;c__[Saprospirae];o__[Saprospirales];f__Chitinophagaceae;g__Flavihumibacter;s__',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': 0.04,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__Methylophilales;f__Methylophilaceae;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.0226666666667,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Acidobacteria;c__BPC102;o__MVS-40;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.0226666666667,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__TM7;c__TM7-1;o__;f__;g__;s__',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': 0.04,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Paenibacillaceae;g__Paenibacillus;s__chondroitinus',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00485714285714,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Deltaproteobacteria;o__Desulfuromonadales;f__Geobacteraceae;g__Geobacter;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00485714285714,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Acidobacteria;c__[Chloracidobacteria];o__;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.0226666666667,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Sphingomonadales;f__Sphingomonadaceae;g__Sphingobium;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00485714285714,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Chloroflexi;c__Anaerolineae;o__S0208;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.0226666666667,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Bacteroidetes;c__Cytophagia;o__Cytophagales;f__Cytophagaceae;g__Dyadobacter;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00485714285714,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Cyanobacteria;c__Chloroplast;o__Chlorophyta;f__Chlamydomonadaceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': 0.00485714285714,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Cyanobacteria;c__Chloroplast;o__Chlorophyta;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.0226666666667,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Chloroflexi;c__Chloroflexi;o__Herpetosiphonales;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.0226666666667,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Actinobacteria;c__Actinobacteria;o__Actinomycetales;f__Micromonosporaceae;g__Actinoplanes;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': 0.0226666666667,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Planctomycetes;c__Planctomycetia;o__B97;f__;g__;s__',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': .04,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Actinobacteria;c__Actinobacteria;o__Actinomycetales;f__Nocardiaceae;g__Nocardia;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .00342857142857,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Chloroflexi;c__TK10;o__;f__;g__;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .00342857142857,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Chloroflexi;c__Anaerolineae;o__A31;f__S47;g__;s__',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': .04,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Actinobacteria;c__Actinobacteria;o__Actinomycetales;f__Intrasporangiaceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .00342857142857,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Elusimicrobia;c__Elusimicrobia;o__Elusimicrobiales;f__;g__;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .00342857142857,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Chloroflexi;c__Chloroflexi;o__AKIW781;f__;g__;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .00342857142857,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__;c__;o__;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': .0266666666667,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Sphingomonadales;f__Sphingomonadaceae;g__Novosphingobium;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .00342857142857,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Chloroflexi;c__Ktedonobacteria;o__Ktedonobacterales;f__Ktedonobacteraceae;g__;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .00342857142857,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Legionellales;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': .0266666666667,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Phyllobacteriaceae;g__Mesorhizobium;s__',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': .04,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Planctomycetes;c__Planctomycetia;o__B97;f__;g__;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .00333333333333,
        'threshold': 90,
    },
    {
        'otu': 'k__Bacteria;p__;c__;o__;f__;g__;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .00333333333333,
        'threshold': 90,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Legionellales;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': .02,
        'threshold': 90,
    },
    {
        'otu': 'k__Bacteria;p__Actinobacteria;c__Actinobacteria;o__Actinomycetales;f__Nakamurellaceae;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': .02,
        'threshold': 90,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Phyllobacteriaceae;g__Mesorhizobium;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .00333333333333,
        'threshold': 90,
    },
    {
        'otu': 'k__Bacteria;p__Planctomycetes;c__Planctomycetia;o__B97;f__;g__;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .002,
        'threshold': 95,
    },
    {
        'otu': 'k__Bacteria;p__Bacteroidetes;c__[Saprospirae];o__[Saprospirales];f__Chitinophagaceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .002,
        'threshold': 95,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Xanthomonadales;f__Xanthomonadaceae;g__Lysobacter;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .006,
        'threshold': 100,
    },
    {
        'otu': 'k__Bacteria;p__Firmicutes;c__Bacilli;o__Bacillales;f__Alicyclobacillaceae;g__Alicyclobacillus;s__',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': .04,
        'threshold': 100,
    },
    {
        'otu': 'k__Bacteria;p__Bacteroidetes;c__Flavobacteriia;o__Flavobacteriales;f__Cryomorphaceae;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': .03,
        'threshold': 100,
    },
]
out = [
    {
        'otu': 'k__Bacteria;p__Acidobacteria;c__Acidobacteria-6;o__;f__;g__;s__',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': .02,
        'threshold': 75,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__A21b',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': .04,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Acidobacteria;c__Acidobacteria-6;o__;f__;g__;s__',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .008,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__Nitrosomonadales;f__Nitrosomonadaceae',
        'freq': 1,
        'pval': 0.02,
        'corrected_pval': .04,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Armatimonadetes;c__[Fimbriimonadia];o__[Fimbriimonadales];f__[Fimbriimonadaceae];g__;s__',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': .04,
        'threshold': 80,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__A21b',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .003,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Deltaproteobacteria;o__Myxococcales;f__Polyangiaceae;g__Sorangium;s__',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': .04,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__Nitrosomonadales;f__Nitrosomonadaceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .003,
        'threshold': 85,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Bradyrhizobiaceae;g__Bradyrhizobium',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .002,
        'threshold': 90,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__A21b',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .002,
        'threshold': 90,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__Nitrosomonadales;f__Nitrosomonadaceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .002,
        'threshold': 90,
    },
    {
        'otu': 'k__Bacteria;p__Actinobacteria;c__Thermoleophilia;o__Solirubrobacterales;f__Solirubrobacteraceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .002,
        'threshold': 90,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Bradyrhizobiaceae;g__Bradyrhizobium',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .002,
        'threshold': 95,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__A21b',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .002,
        'threshold': 95,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__Nitrosomonadales;f__Nitrosomonadaceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .002,
        'threshold': 95,
    },
    {
        'otu': 'k__Bacteria;p__Actinobacteria;c__Thermoleophilia;o__Solirubrobacterales;f__Solirubrobacteraceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .002,
        'threshold': 95,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Bradyrhizobiaceae;g__Bradyrhizobium',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .003,
        'threshold': 100,
    },
    {
        'otu': 'k__Bacteria;p__Actinobacteria;c__Thermoleophilia;o__Solirubrobacterales',
        'freq': 2,
        'pval': 0.04,
        'corrected_pval': .04,
        'threshold': 100,
    },
    {
        'otu': 'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__Nitrosomonadales;f__Nitrosomonadaceae',
        'freq': 0,
        'pval': 0.0,
        'corrected_pval': .003,
        'threshold': 100,
    },
    
]
