#!/bin/bash
TABLE=$1
GROUPFILE=$2
OUTPUT_DIRECTORY=$3

# Directory of script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RESIZE_CMD="python2 $DIR/resize.py"

SIZES=(2 10 25 50)

echo 1
$RESIZE_CMD $TABLE $GROUPFILE $OUTPUT_DIRECTORY/1x1.biom $OUTPUT_DIRECTORY/1x1.tsv -c 1 -r 1
for SIZE in ${SIZES[*]}; do
    echo $SIZE
    $RESIZE_CMD $TABLE $GROUPFILE $OUTPUT_DIRECTORY/${SIZE}x1.biom $OUTPUT_DIRECTORY/${SIZE}x1.tsv -c $SIZE
    $RESIZE_CMD $TABLE $GROUPFILE $OUTPUT_DIRECTORY/1x${SIZE}.biom $OUTPUT_DIRECTORY/1x${SIZE}.tsv -r $SIZE
    $RESIZE_CMD $TABLE $GROUPFILE $OUTPUT_DIRECTORY/${SIZE}x${SIZE}.biom $OUTPUT_DIRECTORY/${SIZE}x${SIZE}.tsv -c $SIZE -r $SIZE
done
